# --- Paths ---
data_path: "data/STR_data/reference_based_labeled_strs/str_len_1_max_cn_perc_0.975_n_flanking_250000.tsv"
ref_path: "data/STR_data/reference_genome/GRCh38_full_analysis_set_plus_decoy_hla.fa"
experiment_name: "str1/dev/dev1"

# --- Data Params (from data.py) ---
batch_size: 512
num_workers: 4
n_flanking_bp: 400
n_str_bp: 6

# --- Model Params (from model.py) ---
hyenaDNA_checkpoint: "LongSafari/hyenadna-tiny-1k-seqlen-hf"
n_prompt_tokens: 8

# --- Strategy: This is the key for this run ---
tuning_strategy: "soft_prompt"

# --- Optimizer ---
optimizer_name: "AdamW"
lr: 1e-4
weight_decay: 0.01

# --- Scheduler ---
scheduler_name: "ReduceLROnPlateau"
scheduler_patience: 3
scheduler_factor: 0.1

# --- Trainer Params ---
max_epochs: 20
patience_early_stopping: 10
gradient_clip_val: 1.0
precision: "bf16-mixed"