# --- Data ---
data_path: "data/STR_data/filtered_labeled_strs/str_len_2_dev.tsv"
ref_path: "data/STR_data/reference_genome/GRCh38_full_analysis_set_plus_decoy_hla.fa"

# --- Model ---
model_path: "scripts/training/output/soft_prompt/str2/v1/str2_l1m_f2000_p128_log_2026-01-12_13-28-53/checkpoints/best-model-epoch=76.ckpt"
desc: "str2/v1/2000_dev_300steps_rt"

# --- IG ---
split: "test"
batch_size: 64
num_workers: 4
n_steps: 300
method: "riemann_trapezoid"
# method: "gausslegendre"