# --- Paths ---
data_path: "data/STR_data/filtered_labeled_strs/str_len_2_max_cn_perc_0.975_n_flanking_10000_filtered.tsv"
ref_path: "data/STR_data/reference_genome/GRCh38_full_analysis_set_plus_decoy_hla.fa"
experiment_name: "lin/str2/str2_f4000_log"

# --- Data Params (from data.py) ---
n_flanking_bp: 4000

# --- Model Params ---
k_values: [3, 4, 5]
log_transform: True
alphas: [1e-4, 1e-3, 1e-2, 0.1, 1, 10, 100, 1000, 1e4, 1e5, 1e6]
seed: 36