# --- Paths ---
data_path: "data/STR_data/HipSTR_labeled_STRs/str_len_3_n_flanking_10000.tsv"
ref_path: "data/reference_genome/GRCh38_full_analysis_set_plus_decoy_hla.fa"
experiment_name: "lin/str3/str3_f5000_sep_dist"

# --- Data Params ---
n_flanking_bp: 5000

# --- Feature Params ---
k_values: [3, 4, 5]
flank_mode: separate        # pooled | separate
distance_bins: [1000, 5000] # bins: [0,1000), [1000,5000)

# --- Model Params ---
alphas: [1e-4, 1e-3, 1e-2, 0.1, 1, 10, 100, 1000, 1e4, 1e5, 1e6]
seed: 36
