# --- Paths ---
data_path: "data/STR_data/reference_based_labeled_strs/str_len_2_max_cn_perc_0.975_n_flanking_250000.tsv"
ref_path: "data/STR_data/reference_genome/GRCh38_full_analysis_set_plus_decoy_hla.fa"
experiment_name: "str2/dev/dev2"

# --- Data Params (from data.py) ---
batch_size: 16
accumulate_grad_batches: 8
num_workers: 4
n_flanking_bp: 8000
n_str_bp: 8
log_transform: False

# --- Model Params (from model.py) ---
hyenaDNA_checkpoint: "LongSafari/hyenadna-small-32k-seqlen-hf"
n_prompt_tokens: 512

# --- Strategy: This is the key for this run ---
tuning_strategy: "soft_prompt"

# --- Optimizer ---
optimizer_name: "Adam"
lr: 1e-4
weight_decay: 0.0

# --- Scheduler ---
scheduler_name: "ReduceLROnPlateau"
scheduler_patience: 5
scheduler_factor: 0.5

# --- Trainer Params ---
max_epochs: 200
patience_early_stopping: 10
gradient_clip_val: 1.0
precision: "bf16-mixed"